name: E2E

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  e2e-podman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: Build podman e2e check
        run: nix build .#checks.x86_64-linux.e2e-podman
